# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'subtlealarm' do
pod 'pop', '~> 1.0'
end

target 'subtlealarmTests' do

end

